spring:
  datasource:
    url: jdbc:mysql://ssmmaintest.cjvmex06e1xk.ap-northeast-2.rds.amazonaws.com:3306/ssmmaintest?useSSL=true&requireSSL=true&serverTimezone=UTC
    username: admin
    password: Code12!!
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          ddl-auto: create
      show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 232398614438-4laehmm9vibdvaa8hv57miuvgpkv33kj.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

server:
  port: 8080
  forward-headers-strategy: NATIVE

logging:
  level:
    org.hibernate.sql: info
    org.hibernate.type: info
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key: CodeStatesMainProject25team
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 360