
spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:~/seb025db  # 파일 기반 H2 데이터베이스 사용
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  jpa-auditing:
    enabled: true

  application:
    name: SsmApplication
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 232398614438-4laehmm9vibdvaa8hv57miuvgpkv33kj.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
              - "https://www.googleapis.com/auth/user.phonenumbers.read"
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    spring:
      mvc:
        converters:
          preferred-json-mapper: jackson
      http:
        converters:
          preferred-json-mapper: jackson

logging:
  level:
    root: INFO
server:
  port: 8888
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key: CodeStatesMainProject25team
  access-token-expiration-minutes: 1
  refresh-token-expiration-minutes: 360

