spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: update  # (3) SQL pretty
  application:
    name: SsmApplication
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 232398614438-4laehmm9vibdvaa8hv57miuvgpkv33kj.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
              - "https://www.googleapis.com/auth/user.phonenumbers.read"
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    spring:
      mvc:
        converters:
          preferred-json-mapper: jackson
      http:
        converters:
          preferred-json-mapper: jackson

logging:
  level:
    root: INFO
server:
  port: 8080
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key: CodeStatesMainProject25team
  access-token-expiration-minutes: 5
  refresh-token-expiration-minutes: 360

