
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:  # 여기에 데이터베이스 비밀번호를 입력하세요

  jpa:
    hibernate:
      ddl-auto: update  # 애플리케이션 시작 시 DB 스키마를 자동으로 업데이트하려면 'update'로 설정합니다
    database-platform: org.hibernate.dialect.H2Dialect

  jpa-auditing:
    enabled: true

  application:
    name: SsmApplication
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 232398614438-4laehmm9vibdvaa8hv57miuvgpkv33kj.apps.googleusercontent.com           # (1)
            clientSecret: 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  # (2)
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

    spring:
      mvc:
        converters:
          preferred-json-mapper: jackson
      http:
        converters:
          preferred-json-mapper: jackson

logging:
  level:
    root: INFO

server:
  port: 8080
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 120
  refresh-token-expiration-minutes: 360
