
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

  application:
    name: SsmApplication
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 232398614438-4laehmm9vibdvaa8hv57miuvgpkv33kj.apps.googleusercontent.com
            clientSecret: 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
            redirect-uri: '{baseUrl}/login/oauth2/code/google'
            scope: openid,profile,email
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    spring:
      mvc:
        converters:
          preferred-json-mapper: jackson
      http:
        converters:
          preferred-json-mapper: jackson

logging:
  level:
    root: INFO
server:
  port: 8888
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key: CodeStatesMainProject25team
  access-token-expiration-minutes: 120
  refresh-token-expiration-minutes: 360

