name: Java CI with Gradle

on:
  push:
    branches: [ feat/be-directory ]

jobs:
  CI:
    env:
      working-directory: ./ssm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x BarkingCat/gradlew
      - name: Build with Gradle
        run: |
          cd BarkingCat
          sudo ./gradlew build
      - name: Build Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: yoongunyong/ssm
          tags: latest
          registry: docker.io
          username: ${{ DOCKER_HUB_USERNAME }}
          password: ${{ DOCKER_HUB_PASSWORD }}

  deploy:
    needs: CI
    name: Deploy
    runs-on: [ self-hosted ]
    steps:
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Docker run
        run: |
          docker stop ssm && docker rm -fv ssm
          docker rmi -f yoongunyong/ssm
          docker run -d -p 8080:8080 --name ssm --restart always yoongunyong/ssm:latest