name: SEB_45_Team025_MainProject

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 스프링부트 애플리케이션 빌드 # (1)
        run: ./gradlew build

      - name: 도커 이미지 빌드
        run: docker build -t rkswlska789/ssm:${{ github.sha }} .

      - name: Docker Hub 퍼블리시
        run: docker push rkswlska789/ssm:${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Start Session Manager session
        run: aws ssm start-session --target i-027d04f3d6691fb34

      - name: Deploy to Server
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
        run: |
          DOCKER_IMAGE_TAG=$(echo "${{ github.sha }}" | cut -c1-7)
          
          aws ssm send-command \
            --instance-ids i-027d04f3d6691fb34 \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=[
              'if sudo docker ps -a --format {{.Names}} | grep -q ^server$; then',
              '  sudo docker stop server',
              '  sudo docker rm server',
              'fi',
              'sudo docker pull rkswlska789/ssm:${DOCKER_IMAGE_TAG}',
              'sudo docker tag rkswlska789/ssm:${DOCKER_IMAGE_TAG} ssm_025',
              'sudo docker run -d --name server -p 8080:8080 ssm_025'
            ]" \
            --output text
